server:
  port: 8004
spring:
  datasource:
    dynamic:
      primary: demo_db
      strict: false
      datasource:
        demo_db:
          url: jdbc:mysql://dev.example.com:3306/demo_db?characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: Z5g@9Bv7<L1qX8d!
          driver-class-name: com.mysql.cj.jdbc.Driver
