server:
  port: 8080
spring:
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:mysql://dev.example.com:3306/testDB?useSSL=false&serverTimezone=UTC
    username: root
    password: 'ZZ0jQ@x@'
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: dev.example.com
      port: 6379
      password: '@XnhiuhtU8_i'
      database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/mapper/**.xml
