server:
  port: 8003
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/employees?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
