## 开启debug日志
debug: true
logging:
  level:
    com.example: debug
  config: classpath:logback-spring.xml
## 自定义配置信息
developer:
  lastName: Kyrie.Wang
  age: 18
  boss: true
  birthday: 2006/2/3
  maps:
    name: sangeng
    age: 11
  maps2: { name: caotang,age: 199 }
  list:
    - name: 小白
      age: 3
    - name: 小黄
      age: 4
    - { name: 小黑,age: 1 }
  dog:
    name: 瓣瓣
    age: 1
  arr:
    - sangeng
    - caotang
  arr2: [ sangeng,caotang ]
  dogMap:
    xb: { name: 小白,age: 9 }
    xh:
      name: 小红
      age: 6
