server:
  port: 8001
  tomcat:
    max-http-form-post-size: 20MB   # 设置内置Tomcat请求大小为20MB
## 静态资源访问设置
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/static/images
  servlet:
    multipart:
      max-request-size: 20MB # 设置请求最大大小为20MB
      max-file-size: 20MB # 设置文件上传最大大小为20MB
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:8000
#  application:
#    name: web-example
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: ALWAYS
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
