server:
  port: 8007
spring:
  application:
    name: spring-boot-redis
  redis:
    database: 0
    host: dev.example.com
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password: ''
    port: 34223
    timeout: 5000ms
  datasource:
    dynamic:
      primary: demo_db
      strict: false
      datasource:
        demo_db:
          url: jdbc:mysql://dev.example.com:3306/demo_db?characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: Z5g@9Bv7<L1qX8d!
          driver-class-name: com.mysql.cj.jdbc.Driver


